spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: root4977
    
#jpa settings
  jpa:
    hibernate:
      ddl-auto: update
      # the above line creates a new db evrytime you re-run the application.
      # you can also use 'update' if you dont wanna drop the db you are using.
      #above code is bare minimum code required to connect to mysql database 
#schema(db) we are using is 'cloud_vendor'.  